[package]
name = "pombase-gocam-process"
version = "0.1.0"
edition = "2021"

[dependencies]
pombase-gocam = { git = "https://github.com/pombase/pombase-gocam.git", version = "0.10.0" }
clap = { version = "4.5.30", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
serde = "1.0"
petgraph = "0.7"
